### ISSUE TITLE
Doesn't show the relative path where the gulp task breaks.

### ISSUE THREAD

**Issue by anweshknayak** [AndiDittrich/gulp-prettyerror#6]

**Comment by AndiDittrich** [comment]
Right, it shows the absolute path - what's wrong with that ?

![Screenshot](https://github.com/AndiDittrich/gulp-prettyerror/raw/master/screenshot1.jpg)

**Comment by anweshknayak** [comment]
@AndiDittrich it doesn't when I used the plugin in my project ? any help here ?

**Comment by AndiDittrich** [comment]
could you please post a simple example ? does it output nothing or only `"Build Error in <pluginname>"`

**Comment by anweshknayak** [comment]
[21:17:52] |- Build Error in gulp-uglify
[21:17:52] |- unable to minify JavaScript

**Comment by AndiDittrich** [comment]
**gulp-uglify** right ? i can reproduce the issue - currently **gulp-prettyerror** is only using the `codeFrame` object to display additional data, but **gulp-uglify** throws a `JS_Parse_Error`

i will add an additional output handler to show up such errors - thank you for reporting it!

**Comment by AndiDittrich** [comment]
Please try the latest version from GitHub - it should look like this in case `error.cause` object is provided (e.g. gulp-uglify)

![gulp-prettyerror-uglifyjs](https://cloud.githubusercontent.com/assets/1474107/22398038/5bb08454-e57f-11e6-916e-4e28c82fa6ae.jpg)

**Comment by anweshknayak** [comment]
Thanks @AndiDittrich
